[package]
name = "csv_challenge"
version = "0.1.0"
authors = ["陶辰 <chen.tao@ifchange.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.14"
structopt-derive = "0.4.7"
